deployment:
  name: "weatherapp"
  replicas: "1"
  image: "michaelaviram/weatherapp"
  containerPort: "8989"
  configmap: "blue"
  configmapKey: "BG_COLOR"

service:
  name: "weatherapp-service"
  port: "8989"
  targetPort: "8989"

configmaps:
  first:
    name: "blue"
    color: "green"
  second:
    name: "green"
    color: "green"

ingress:
  name: "weatherapp-ingress"
  className: "nginx"
  path: "/"
